version: 2

before:
  hooks:
    - go mod tidy
    # We assume frontend is built in the CI workflow BEFORE running goreleaser to avoid dependency on node in the goreleaser environment itself if possible, 
    # OR we can add a hook here. Since we are using standard GitHub Actions, it's cleaner to do the "npm build" step in the workflow yml 
    # and simply ensure the files are there. 
    # However, to be safe, we can leave this empty or add a check.

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # this name template makes the release distribution files look like directory structures
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
